// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package club.virgilin.proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:club.virgilin.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .club.virgilin.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<club.virgilin.proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .club.virgilin.proto.StudentResponse studentResponse = 1;</code>
   */
  club.virgilin.proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .club.virgilin.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .club.virgilin.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends club.virgilin.proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .club.virgilin.proto.StudentResponse studentResponse = 1;</code>
   */
  club.virgilin.proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
